import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import WorkoutContext from "@/context/WorkoutContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
    lang="en"
    className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
>
    <body className="min-h-screen flex flex-col bg-[#0d0f12] text-white">

        <WorkoutContext>

            <Navbar />

            <div className="flex-1 w-full container mx-auto max-w-320">
                {children}
            </div>

            <Footer />

            <ToastContainer />

        </WorkoutContext>

    </body>
</html>
  );
}
